name: SwiftOnLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache ninja
      id: cache-ninja
      uses: actions/cache@v1
      with:
        path: "~/ninja"
        key: ${{ runner.os }}-ninja

    - name: Prepare ninja
      run: |
        sudo apt-get install ninja-build
    
    - name: locate swift
      uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.3' # This value is passed to swiftenv without modification.

    - name: Configure cmake
      run: |
        whereis swiftc
        cmake -G Ninja -B build

    - name: Build
      run: cd build; ninja
